### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'value')

### ISSUE THREAD

**Issue by eikelben** [albertc44/coda-google-apps-script#4]
I have numerous instances of this script running successfully but none with anything as large as the table in question here.  I am attempting to sync an array of 4,000 rows x 32 columns and keep getting the following error:

`TypeError: Cannot read properties of undefined (reading 'value')
(anonymous)	@ sheetsToCoda.gs:288
convertValuesForSheets	@ sheetsToCoda.gs:285
updateCoda	@ sheetsToCoda.gs:97
runSync	@ sheetsToCoda.gs:39`

The initial sync seems to run fine; its is with subsequent syncs that the error occurs.  It is unclear to me whether this is because the table simply exceeds some limit or whether there is another issue going on.  Any help would be greatly appreciated.  

Similar issue: [here](https://community.coda.io/t/google-sheets-to-coda-error/36685/7)

Note, deleting the coda table and resetting up the sync worked successfully the first time, then errored out as it did previously.

**Comment by thealchen** [comment]
@eikelben Hard to say without looking at the Coda doc or Google Sheets. I'm guessing you've checked to see if the column names match _exactly_? No trailing/leading spaces, case sensitivity, etc.

**Comment by eikelben** [comment]
@al-codaio understood.  Yes, I've confirmed the column names are indeed exact with no trailing spaces, etc.  The confusing part is the first sync always runs fine and pulls in all 3979 rows.  It's when I attempt to run it again that it generates the error (I've tested running it with and without an actual discrepancy in the dataset to see whether the lack of any difference between the two was causing the error).  

Some years back when you originally posted this, you indicated that you were optimistic about a native way to handle scenarios like this.  Is this script still the best method?  I've also been considering Paul Danyliuk's pack, Sync Tables Pro to see if that would solve my issues.  We, unfortunately, have some things we cannot fully move over to Coda so bridging this gap is something I need a longterm solution for.

**Comment by thealchen** [comment]
@eikelben Hm I've never seen this error before where the first sync works but subsequent syncs don't work. A few quick questions along with why I'm asking these questions:

1. **Are all the Source Row URLs present in your Google Sheet?** - I think if you see certain rows missing a Source Row URL from Coda, that might lead to some issues with the sync.
2. **How quickly are you running the 2nd sync after the 1st sync?** - Coda requires a few seconds to "snapshot" data after it's been inputted into a table. If you run the 2nd sync (and subsequent syncs) too closely together, there may be some data discrepancies between Sheets and Coda.

We are planning on releasing a native Google Sheets Pack in the coming months. There are also some free [Google Sheets Packs](https://coda.io/gallery/search?q=google%20sheets) created by the community that you might try experimenting with in the meantime.

**Comment by eikelben** [comment]
Hi @al-codaio, answers below although I fear they're not too helpful.  I'm taking some time today to explore Paul Danyliuk's pack.  What I'm looking for is a robust long term solution to massage Coda into being more of a database where I import a few base tables (employees, projects, product item master, etc) that I can then create views from that feed all of our coda docs.  As it stands currently I'm using the script to get them into coda to then cross-doc views and I'm running into–not a lot but–too many glitches in order to make me feel confident in recommending this as a company-wide path forward.  Do you see the native google sheets pack as a solution for this sort of use case?  In order words, am I better off waiting a few months to see what you guys develop versus implementing a different pack-based solution now? 

1. Source row URLs are present for all rows (additionally I've deleted any blank rows from the bottom of the table as well just to be sure that wasn't having any impact.  
2. I haven't sync'd since yesterday and just ran it again with the same error, so 12+ hours.

**Comment by thealchen** [comment]
@eikelben In terms of moving forward, I think if you're able to get one of the existing Packs to work (and you don't see as many glitches), then go with that Pack. I'm not sure how much better/worse the native Google Sheets Pack will be, but the only way to find out is to test them for your specific use case. Looking at the error a little more, I think the error is on the Coda side since that `convertValuesForSheets` functions is reading your Coda table and doing some transformations to get that data ready to sync into Sheets. For whatever reason, it can't "read" some of the values in the table. Wish I could help debug further but hard to do without seeing the actual data.

**Comment by eikelben** [comment]
@al-codaio thanks for investigating this with me.  I tried out all of the available packs and unfortunately am working through issues with each one of them directly with their respective developers.

This ability is nothing short of a necessity for many Coda users so hopefully it is being prioritized as such.  Fortunately both of your scripts have worked well up to this point, but it would appear something changed recently as I'm running into more issues with tables appearing to sync successfully then finding duplicate (or missing) rows or the script throwing an error but visually appearing to be correct.  Unfortunately, all of my forward progress is going to be halted until a robust solution can be had for this as I need to make 10+ views for each master table and tie those back into existing tables in Coda…
